INSERT INTO `Achievement`
    (`id`, `name`,`description`)
VALUES
    (1, 'Let"s make bourbone', 'Collect 1000 of corn'),
    (2, 'Chicken Town','Build 10 Chicken Houses'),
    (3, 'Granary Fan','Upgrad Granary 15 times'),
    (4, 'I am ready for the fifth labour of Heracles','Get 5 Chicken Houses and 1000 dung'),
    (5, 'Mad Scrooge','Collect 10000 of corn(in all)'),
    (6, 'Bazoookas Boy','Get 200 cocks with bazookas'),
    (7, 'Shity Kingdom','Collect 1000 cocks and 10 Cocks Barrack'),
    (8, 'Gladiator arena','Get 200 cocks-swordman and 5 wsordman-sckool'),
    (9, 'Arow in tht Knee','Get 100 Cock-Archers'),
    (10, 'Whats up Satan','Get 666 Wizards'),
    (11, 'Pick-up master','Collect 10000 Chicks(in all)'),
    (12, 'Cocks Fight club','Get 150 fighting cock'),
    (13, '300 Cock-Spartan','Get 300 cock with axes'),
    (14, 'And you think this is a big gun?','make 100 Guns'),
    (15, 'I see dead cocks...','Make 100 cock-prophet'),
    (16, 'I am 12 and i love Minecraft','Craft 2000 Stones'),
    (17, 'Lets make Booooom','Collect 2000 gunpowder(in all)'),
    (18, 'I have enough steel to be an Ironman','Collect 5000 of steel'),
    (19, 'Eggs better that War','Collect 5000 of eggs and upgrade 10 Chicken Houses'),
    (20, 'Hogwarts', 'Collect 4 School of Mages and 200 cocks magicians'),
    (21, 'Robin Good', 'Upgrade 5 School of Archers and collect 500 wood'),
    (22, 'You are SuperCock', 'Upgrade 10 Cocks House, make 10 Cocks House and collect 10000 cocks');