INSERT INTO `Card`
    (`id`,`name`,`description`)
VALUES
		(1,'Build Granary','Building Card'),
		(2,'Build Chicken House','Building Card'),
		(3,'Build Incubator','Building Card'),
		(4,'Build Cleaning Center','Building Card'),
		(5,'Build Chicken Yard','Building Card'),
		(6,'Build Cocks House','Building Card'),
		(7,'Build Cocks Barrack','Building Card'),
		(8,'Build Quarry','Building Card'),
		(9,'Build School of Hammers','Building Card'),
		(10,'Build School of Throwings','Building Card'),
		(11,'Build Blast Furnace','Building Card'),
		(12,'Build School of Swordsmens','Building Card'),
		(13,'Build School of Axes','Building Card'),
		(14,'Build Logger','Building Card'),
		(15,'Build School of Archers','Building Card'),
		(16,'Build School of Lancers','Building Card'),
		(17,'Build Alchemy Laboratory','Building Card'),
		(18,'Build School of Gunners','Building Card'),
		(19,'Build School of Bazookas','Building Card'),
		(20,'Build Altar','Building Card'),
		(21,'Build School of Mages','Building Card'),
		(22,'Build Ziggurat','Building Card'),
		(23,'Upgrade Granary','Upgrading Card'),
		(24,'Upgrade chiken house','Upgrading Card'),
		(25,'Initialize the chiken','Upgrading Card'),
		(26,'F@ck this, i`m out','Upgrading Card'),
		(27,'Glue a chick','Upgrading Card'),
		(28,'Ruffle up a chiken','Upgrading Card'),
		(29,'Mother-in-law? I`m in the army','Upgrading Card'),
		(30,'Minecraft?','Upgrading Card'),
		(31,'USSC','Upgrading Card'),
		(32,'Sling? Nooooo','Upgrading Card'),
		(33,'Steelworkers','Upgrading Card'),
		(34,'Chicken infantry','Upgrading Card'),
		(35,'Clumsy fame','Upgrading Card'),
		(36,'New saws','Upgrading Card'),
		(37,' Add optical sight to all bow','Upgrading Card'),
		(38,'Training of lancers','Upgrading Card'),
		(39,'Crazy professor','Upgrading Card'),
		(40,'Add fire transfer pen','Upgrading Card'),
		(41,'ChiRambo','Upgrading Card'),
		(42,'Meditation','Upgrading Card'),
		(43,'Kill the Witcher','Upgrading Card'),
		(44,'Life for Ner` Zul','Upgrading Card'),
		(45,'Pesticides','Upgrading Card'),
		(46,'Broiler','Upgrading Card'),
		(47,'Red bull','Upgrading Card'),
		(48,'Muscle gym','Upgrading Card'),
		(49,'New armor','Upgrading Card'),
		(50,'Steel feathers','Upgrading Card'),
		(51,'Armed and dangerous','Upgrading Card'),
		(52,'Disney Princess? Really?','Upgrading Card'),
		(53,'Attack Enemy by battle cocks','Action Card'),
		(54,'master`s feast','Action Card'),
		(55,'Elixir of youth','Action Card'),
		(56,'hungry fox','Action Card'),
		(57,'attack Enemy by cocks with hammers','Action Card'),
		(58,'attack Enemy by cocks with Throwings','Action Card'),
		(59,'Thief of shit','Action Card'),
		(60,'Army of Mouse','Action Card');