insert into upgrade (id, name, description) values
(1, 'Upgrade Granary', 'no comment'),
(2, 'Upgrade Granary and chikens house', 'no comment'),
(3, 'Initialize the chikens', 'no comment'),
(4, 'F@ck this, i`m out', 'no comment'),
(5, 'Glue a chickens', 'no comment'),
(6, 'Ruffle up a chikens', 'no comment'),
(7, 'Mother-in-law? I`m in the army', 'no comment'),
(8, 'Minecraft?', 'no comment'),
(9, 'USSC', 'no comment'),
(10, 'Sling? Nooooo', 'no comment'),
(11, 'Steelworkers', 'no comment'),
(12, 'Chickens infantry', 'no comment'),
(13, 'Clumsy fame', 'no comment'),
(14, 'New saws', 'no comment'),
(15, 'Add optical sight to all bow', 'no comment'),
(16, 'Training of lancers', 'no comment'),
(17, 'Crazy professor', 'no comment'),
(18, 'Add fire transfer pen', 'no comment'),
(19, 'ChiRambo', 'no comment'),
(20, 'Meditation', 'no comment'),
(21, 'Kill the Witcher', 'no comment'),
(22, 'Life for Ner` Zul', 'no comment'),
(23, 'Pesticides', 'no comment'),
(24, 'Broiler', 'no comment'),
(25, 'Red bull', 'no comment'),
(26, 'Muscle gym', 'no comment'),
(27, 'New armor', 'no comment'),
(28, 'Steel feathers', 'no comment'),
(29, 'Armed and dangerous', 'no comment'),
(30, 'Disney Princess? Really?', 'no comment');

